import { act, renderHook } from "@testing-library/react";
import { expect, it, vi } from "vitest";
import { useCompletionState } from "./useCompletionState";
import { DocumentSession } from "../../features/documents/DocumentSession";
const fetchMock = vi.hoisted(() => vi.fn());
const cancelMock = vi.hoisted(() => vi.fn().mockResolvedValue({ ok: true, data: true }));
vi.mock("../../lib/ipc/client", () => ({ fetchWorkspaceCompletions: fetchMock, cancelLanguageRequest: cancelMock }));
it("invalidates completion reuse and rejects pending results when another Go buffer changes", async () => {
  fetchMock.mockReset();
  const session = new DocumentSession(); session.reset("C:/original");
  const other = session.open("other.go", "package main\nvar Old = 1\n"); const main = session.open("main.go", "package main\nfunc main(){}\n");
  let resolve!: (value: unknown) => void;
  fetchMock.mockImplementation(() => new Promise(done => { resolve = done; }));
  const workspacePathRef = { current: "C:/original" }, activeFilePathRef = { current: "main.go" }, latestEditorContentRef = { current: main.text };
  const hook = renderHook(({ snapshot }) => useCompletionState({ documentSnapshot: snapshot, workspacePathRef, activeFilePathRef, latestEditorContentRef, activeFileContent: main.text }), { initialProps: { snapshot: session.snapshot() } });
  const previous = hook.result.current.handleRequestCompletions; let pending!: Promise<unknown>;
  act(() => { pending = previous({ line: 2, column: 1, explicit: true }); });
  session.edit(other.id, "package main\nvar New = 2\n"); hook.rerender({ snapshot: session.snapshot() });
  expect(hook.result.current.handleRequestCompletions).not.toBe(previous);
  await act(async () => { resolve({ ok: true, data: [{ label: "Old", insertText: "Old" }] }); expect(await pending).toEqual([]); });
  hook.unmount();
});
it("does not cancel a fresh model request when React commits the same keystroke", async () => {
  fetchMock.mockReset(); cancelMock.mockClear();
  let resolve!: (value: unknown) => void;
  fetchMock.mockImplementation(() => new Promise(done => { resolve = done; }));
  const workspacePathRef = { current: "C:/original" }, activeFilePathRef = { current: "main.go" };
  const latestEditorContentRef = { current: "package main\nfunc main(){fmt.}" };
  const hook = renderHook(({ content }) => useCompletionState({ workspacePathRef, activeFilePathRef, latestEditorContentRef, activeFileContent: content }), { initialProps: { content: "package main\nfunc main(){fmt}" } });
  let pending!: Promise<unknown>;
  act(() => { pending = hook.result.current.handleRequestCompletions({ line: 2, column: 17, explicit: false, fileContent: latestEditorContentRef.current }); });
  hook.rerender({ content: latestEditorContentRef.current });
  expect(cancelMock).not.toHaveBeenCalled();
  await act(async () => { resolve({ ok: true, data: [{ label: "Println", insertText: "Println" }] }); expect(await pending).toEqual([{ label: "Println", insertText: "Println" }]); });
  hook.unmount();
});
it("sends exact unsaved Go tabs and a virtual completion buffer without saving", async () => {
  fetchMock.mockReset().mockResolvedValue({ ok: true, data: [] });
  const session = new DocumentSession(); session.reset("C:/original");
  session.open("other.go", "package main\nvar Unsaved = 1\n"); session.open("README.md", "# notes"); session.open("main.go", "package main\nfunc main() {}\n");
  const hook = renderHook(() => useCompletionState({ documentSnapshot: session.snapshot(), workspacePathRef: { current: "C:/original" }, activeFilePathRef: { current: "main.go" }, latestEditorContentRef: { current: session.active!.text }, activeFileContent: session.active!.text }));
  await act(async () => { await hook.result.current.handleRequestCompletions({ line: 3, column: 8, explicit: false, fileContent: 'package main\nimport "fmt"\nfmt.\n' }); });
  expect(fetchMock).toHaveBeenCalledWith(expect.objectContaining({ buffers: [{ path: "other.go", content: "package main\nvar Unsaved = 1\n" }, { path: "main.go", content: 'package main\nimport "fmt"\nfmt.\n' }] }));
  expect(session.active!.text).toBe("package main\nfunc main() {}\n"); hook.unmount();
});

it("cancels an aborted popup request immediately without cancelling its successor", async () => {
  fetchMock.mockClear(); cancelMock.mockClear();
  const pending: Array<(result: unknown) => void> = [];
  fetchMock.mockImplementation(() => new Promise(resolve => pending.push(resolve)));
  const hook = renderHook(() => useCompletionState({ workspacePathRef: { current: "C:/original" }, activeFilePathRef: { current: "main.go" }, latestEditorContentRef: { current: "package main" }, activeFileContent: "package main" }));
  const firstController = new AbortController();
  let first!: Promise<unknown>, second!: Promise<unknown>;
  act(() => { first = hook.result.current.handleRequestCompletions({ line: 1, column: 1, explicit: false, signal: firstController.signal } as any); });
  const request1 = fetchMock.mock.calls[0][0];
  act(() => firstController.abort());
  expect(cancelMock).toHaveBeenLastCalledWith({ workspaceRoot: "C:/original", requestId: request1.requestId });
  act(() => { second = hook.result.current.handleRequestCompletions({ line: 1, column: 2, explicit: false }); });
  await act(async () => { pending[0]({ ok: true, data: [{ label: "obsolete" }] }); expect(await first).toEqual([]); });
  await act(async () => { pending[1]({ ok: true, data: [{ label: "Println" }] }); expect(await second).toEqual([{ label: "Println" }]); });
  expect(hook.result.current.completionAvailability).toBe("available");
  hook.unmount(); fetchMock.mockClear(); cancelMock.mockClear();
});

it("cancels native completion on supersession, edits, workspace changes and unmount", async () => {
  const workspacePathRef = { current: "C:/original" as string | null };
  const activeFilePathRef = { current: "main.go" as string | null };
  const latestEditorContentRef = { current: "package main\n" as string | null };
  const pending: Array<(result: unknown) => void> = [];
  fetchMock.mockImplementation(() => new Promise(resolve => pending.push(resolve)));
  const hook = renderHook(() => useCompletionState({ workspacePathRef, activeFilePathRef, latestEditorContentRef, activeFileContent: latestEditorContentRef.current }));
  let first!: Promise<unknown>, second!: Promise<unknown>;
  act(() => { first = hook.result.current.handleRequestCompletions({ line: 1, column: 1, explicit: true }); });
  const request1 = fetchMock.mock.calls[0][0];
  act(() => { second = hook.result.current.handleRequestCompletions({ line: 1, column: 2, explicit: true }); });
  const request2 = fetchMock.mock.calls[1][0];
  expect(cancelMock).toHaveBeenLastCalledWith({ workspaceRoot: "C:/original", requestId: request1.requestId });
  await act(async () => { pending[0]({ ok: true, data: [{ label: "obsolete" }] }); expect(await first).toEqual([]); });
  act(() => hook.result.current.invalidateCompletionRequests());
  expect(cancelMock).toHaveBeenLastCalledWith({ workspaceRoot: "C:/original", requestId: request2.requestId });
  await act(async () => { pending[1]({ ok: false, error: { message: "cancelled" } }); expect(await second).toEqual([]); });
  act(() => { void hook.result.current.handleRequestCompletions({ line: 1, column: 1, explicit: true }); });
  const request3 = fetchMock.mock.calls[2][0];
  workspacePathRef.current = "C:/new";
  hook.rerender();
  expect(cancelMock).toHaveBeenLastCalledWith({ workspaceRoot: "C:/original", requestId: request3.requestId });
  act(() => { void hook.result.current.handleRequestCompletions({ line: 1, column: 1, explicit: true }); });
  const request4 = fetchMock.mock.calls[3][0];
  hook.unmount();
  expect(cancelMock).toHaveBeenLastCalledWith({ workspaceRoot: "C:/new", requestId: request4.requestId });
});
